In [3]:
import numpy as np
import cv2 

### 加法运算

In [6]:
# 图像本质上是ndarray(矩阵), ndarray的加法运算要求两个矩阵的shape必须完全一致. 
# ndarray的加法: 对应位置的元素进行相加
cat = cv2.imread('./cat.jpeg')
dog = cv2.imread('./dog.jpeg')
print(cat.shape, dog.shape)
# 如果shape不同, 会尝试进行广播. 
# 1. 维度不够会补维度. 2. 会用已有的数据进行填充. 
# cat + dog
# cv2.add(cat, dog)
# 可以对猫的图片进行裁剪, 裁剪出狗的大小, 不太推荐. 
# opencv中修改图片大小的函数: resize
# ndarray中行数是高度, 列数是宽度. 
# resize中是先宽度, 再高度. 
new_dog = cv2.resize(dog, (640, 480))

# opencv 的add方法会让超过255的数, 全部变成255, 相当于做了截断. 
img = cv2.add(cat, new_dog)
# ndarray的加法, 会产生大于255的数据, 又因为数据类型是uint8的类型, 就会% 256, 用余数来填充. 
# img = cat + new_dog

cv2.imshow('img', np.hstack((cat, new_dog, img)))
cv2.waitKey(0)
cv2.destroyAllWindows()

(480, 640, 3) (360, 499, 3)


In [15]:
# 因为是uint8的类型, 所以不会超过255. 但是超了怎么办. 
np.max(img)

255

In [16]:
cat[:3, :3]

array([[[204, 203, 205],
        [205, 204, 206],
        [206, 205, 207]],

       [[204, 203, 205],
        [205, 204, 206],
        [206, 205, 207]],

       [[204, 203, 205],
        [204, 203, 205],
        [205, 204, 206]]], dtype=uint8)

In [33]:
204 / 215 

0.9488372093023256

In [34]:
203 / 175

1.16

In [17]:
dog[:3, :3]

array([[[215, 175, 140],
        [216, 176, 141],
        [220, 178, 143]],

       [[222, 180, 145],
        [222, 180, 145],
        [220, 178, 143]],

       [[225, 180, 146],
        [223, 181, 146],
        [223, 181, 146]]], dtype=uint8)

In [ ]:
204 + 215 = 163

In [19]:
204 + 215

419

In [21]:
419 % 256

163

In [18]:
img[:3, :3]

array([[[163, 122,  89],
        [164, 123,  91],
        [168, 126,  93]],

       [[167, 125,  92],
        [169, 126,  93],
        [170, 127,  94]],

       [[171, 127,  94],
        [171, 127,  94],
        [171, 128,  95]]], dtype=uint8)

In [23]:
# opencv 的add之后的结果
img[:3, :3]

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

### 图像的减法运算

In [29]:
cat = cv2.imread('./cat.jpeg')
dog = cv2.imread('./dog.jpeg')

 
new_dog = cv2.resize(dog, (640, 480))
 
# 如果减完之后, 小于0, 那么统一变成0
img = cv2.subtract(cat, new_dog)

# img = cat - new_dog

cv2.imshow('img', np.hstack((cat, new_dog, img)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
img[20:50, 150:200]

array([[[ 0,  0, 30],
        [ 0,  0, 25],
        [ 0,  1, 31],
        ...,
        [ 0,  0, 18],
        [ 0,  0, 11],
        [ 0,  0, 11]],

       [[ 0,  0, 26],
        [ 0,  0, 22],
        [ 0,  0, 29],
        ...,
        [ 0,  0, 25],
        [ 0,  0, 16],
        [ 0,  0, 12]],

       [[ 0,  0, 28],
        [ 0,  0, 24],
        [ 0,  0, 19],
        ...,
        [ 0,  0, 32],
        [ 0,  0, 34],
        [ 0,  1, 36]],

       ...,

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]], dtype=uint8)

### 图像的乘法和除法


In [30]:
# 乘法
cat = cv2.imread('./cat.jpeg')
dog = cv2.imread('./dog.jpeg')

 
new_dog = cv2.resize(dog, (640, 480))
 
# 超过255, 全部变成255
img = cv2.multiply(cat, new_dog)

# img = cat - new_dog

cv2.imshow('img', np.hstack((cat, new_dog, img)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
# 除法
cat = cv2.imread('./cat.jpeg')
dog = cv2.imread('./dog.jpeg')

 
new_dog = cv2.resize(dog, (640, 480))
 

img = cv2.divide(cat, new_dog)

# img = cat - new_dog

cv2.imshow('img', np.hstack((cat, new_dog, img)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
img[:3, :3]

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=uint8)

### 图像的融合

In [39]:
# cv2.addWeighted
cat = cv2.imread('./cat.jpeg')
dog = cv2.imread('./dog.jpeg')

 
new_dog = cv2.resize(dog, (640, 480))
 

img = cv2.addWeighted(cat, 0.2, new_dog, 0.8, 0)

# img = cat - new_dog

cv2.imshow('img', np.hstack((cat, new_dog, img)))
cv2.waitKey(0)
cv2.destroyAllWindows()

## 图像的位运算

In [ ]:
# 图像的位运算就是对图像进行与或非, 异或.

### 与运算

In [45]:
cat = cv2.imread('./cat.jpeg')
dog = cv2.imread('./dog.jpeg')

 
new_dog = cv2.resize(dog, (640, 480))
 

img = cv2.bitwise_and(cat, new_dog)

# img = cat - new_dog

cv2.imshow('img', np.hstack((cat, new_dog, img)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [42]:
cat[:3, :3]

array([[[204, 203, 205],
        [205, 204, 206],
        [206, 205, 207]],

       [[204, 203, 205],
        [205, 204, 206],
        [206, 205, 207]],

       [[204, 203, 205],
        [204, 203, 205],
        [205, 204, 206]]], dtype=uint8)

In [43]:
new_dog[:3, :3]

array([[[215, 175, 140],
        [215, 175, 141],
        [218, 177, 142]],

       [[219, 178, 143],
        [220, 178, 143],
        [220, 178, 143]],

       [[223, 180, 145],
        [223, 180, 145],
        [222, 180, 145]]], dtype=uint8)

In [53]:
204 | 215

223

In [44]:
204 & 215

196

In [46]:
~204

-205

In [41]:
img[:3, :3]

array([[[196, 139, 140],
        [197, 140, 140],
        [202, 129, 142]],

       [[200, 130, 141],
        [204, 128, 142],
        [204, 128, 143]],

       [[204, 128, 129],
        [204, 128, 129],
        [204, 132, 128]]], dtype=uint8)

### 非运算

In [47]:
cat = cv2.imread('./cat.jpeg')
dog = cv2.imread('./dog.jpeg')

 
new_dog = cv2.resize(dog, (640, 480))
 
# 相当于255 - cat
img = cv2.bitwise_not(cat)

# img = cat - new_dog

cv2.imshow('img', np.hstack((cat, new_dog, img)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [48]:
cat[:3, :3]

array([[[204, 203, 205],
        [205, 204, 206],
        [206, 205, 207]],

       [[204, 203, 205],
        [205, 204, 206],
        [206, 205, 207]],

       [[204, 203, 205],
        [204, 203, 205],
        [205, 204, 206]]], dtype=uint8)

In [50]:
~204

-205

In [51]:
255 - 204

51

In [49]:
img[:3, :3]

array([[[51, 52, 50],
        [50, 51, 49],
        [49, 50, 48]],

       [[51, 52, 50],
        [50, 51, 49],
        [49, 50, 48]],

       [[51, 52, 50],
        [51, 52, 50],
        [50, 51, 49]]], dtype=uint8)

### 或运算

In [52]:
cat = cv2.imread('./cat.jpeg')
dog = cv2.imread('./dog.jpeg')

 
new_dog = cv2.resize(dog, (640, 480))
 

# 对应位置元素进行或运算. 
img = cv2.bitwise_or(cat, new_dog)

# img = cat - new_dog

cv2.imshow('img', np.hstack((cat, new_dog, img)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [54]:
img[:3, :3]

array([[[223, 239, 205],
        [223, 239, 207],
        [222, 253, 207]],

       [[223, 251, 207],
        [221, 254, 207],
        [222, 255, 207]],

       [[223, 255, 221],
        [223, 255, 221],
        [223, 252, 223]]], dtype=uint8)

### 异或运算

In [56]:
cat = cv2.imread('./cat.jpeg')
dog = cv2.imread('./dog.jpeg')

 
new_dog = cv2.resize(dog, (640, 480))
 

# 对应位置元素进行异或运算. 
img = cv2.bitwise_xor(cat, new_dog)

# img = cat - new_dog

cv2.imshow('img', np.hstack((cat, new_dog, img)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [58]:
204 ^ 215

27

In [57]:
img[:3, :3]

array([[[ 27, 100,  65],
        [ 26,  99,  67],
        [ 20, 124,  65]],

       [[ 23, 121,  66],
        [ 17, 126,  65],
        [ 18, 127,  64]],

       [[ 19, 127,  92],
        [ 19, 127,  92],
        [ 19, 120,  95]]], dtype=uint8)

In [5]:
import cv2
import numpy as np

#创建一张图片
img = np.zeros((200,200), np.uint8)
img2 = np.zeros((200,200), np.uint8)

img[20:120, 20:120] = 255
img2[80:180, 80:180] = 255

# new_img = cv2.bitwise_not(img)
# new_img = cv2.bitwise_and(img, img2)
# new_img = cv2.bitwise_or(img, img2)
new_img = cv2.bitwise_xor(img, img2)


cv2.imshow('new_img', np.hstack((img, img2, new_img)))
cv2.waitKey(0)

cv2.destroyAllWindows()