In [367]:
import numpy as np
np.set_printoptions(suppress=True)

In [399]:
def linear_z(x,w,b):
    return x@w + b
def sigmoid_a(z):
    return 1/(1+np.exp(-z))

In [406]:
def dz_a(w,dz):
    return  dz@w.T
def da_z(a,da):
    return da*(a*(1-a))


In [411]:
def dz_w(dz,a):
    return (a.T @ dz)/20
def dz_b(dz):
    return dz.mean(axis =0)

In [455]:
X = np.random.randint(0,120,(20,12))
y = np.random.randint(0,2,(20,1))
W1 = np.random.randn(12,6)
B1 = np.zeros((1,6))
W2 = np.random.randn(6,4)
B2= np.zeros((1,4))
W3 = np.random.randn(4,2)
B3= np.zeros((1,2))
W4 = np.random.randn(2,1)
B4= np.zeros((1,1))
n = 3001
learning = 0.15*n/(n+1)

X_ = (X-X.mean(axis = 0))/X.std(axis=0)

while n:

    z1 = linear_z(X_,W1,B1)
    a1 = sigmoid_a(z1)
    z2 = linear_z(a1,W2,B2)
    a2 = sigmoid_a(z2)
    z3 = linear_z(a2,W3,B3)
    a3 = sigmoid_a(z3)
    z4 = linear_z(a3,W4,B4)
    a4 = sigmoid_a(z4)
 
    j = -y*(a4) - (1-y)*(1-a4)

    dz4 = (a4-y)
    da3 = dz_a(W4,dz4)
    dz3 = da_z(a3,da3)
    da2 = dz_a(W3,dz3)
    dz2 = da_z(a2,da2)
    da1 = dz_a(W2,dz2)
    dz1 = da_z(a1,da1)
 
    dw4 = dz_w(dz4,a3)
    dw3 = dz_w(dz3,a2)
    dw2 = dz_w(dz2,a1)
    dw1 = dz_w(dz1,X)

    db4 = dz_b(dz4)
    db3 = dz_b(dz3)
    db2 = dz_b(dz2)
    db1 = dz_b(dz1)
 

    W1 = W1 - learning * dw1
    B1 = B1 - learning * db1.T
    W2 = W2 - learning * dw2
    B2 = B2 - learning * db2.T
    W3 = W3 - learning * dw3
    B3 = B3 - learning * db3.T
    W4 = W4 - learning * dw4
    B4 = B4 - learning * db4.T
    
    n-=1
    if (3000-n)%150 == 0:
        print(3000-n)
        print(np.round(a4.T,3))
        print(y.T)
        print(j.sum())
        print('_____________')
        

0
[[0.659 0.605 0.633 0.661 0.652 0.649 0.658 0.61  0.66  0.624 0.624 0.657
  0.664 0.645 0.605 0.656 0.617 0.663 0.663 0.629]]
[[0 1 1 1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0]]
-9.76025367441646
_____________
150
[[0.412 0.437 0.494 0.536 0.505 0.478 0.482 0.522 0.521 0.429 0.403 0.526
  0.552 0.443 0.395 0.485 0.391 0.396 0.535 0.396]]
[[0 1 1 1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0]]
-10.783742030245968
_____________
300
[[0.28  0.494 0.538 0.647 0.586 0.496 0.434 0.615 0.649 0.393 0.294 0.614
  0.661 0.525 0.281 0.609 0.283 0.285 0.619 0.289]]
[[0 1 1 1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0]]
-12.149910256626047
_____________
450
[[0.161 0.606 0.74  0.802 0.711 0.432 0.274 0.767 0.794 0.199 0.176 0.722
  0.793 0.307 0.175 0.695 0.162 0.167 0.755 0.165]]
[[0 1 1 1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0]]
-14.580901016853577
_____________
600
[[0.101 0.716 0.844 0.881 0.81  0.276 0.151 0.843 0.86  0.112 0.104 0.781
  0.845 0.209 0.15  0.67  0.092 0.098 0.843 0.094]]
[[0 1 1 1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0]