### 图像金字塔之高斯金字塔

In [1]:
import numpy as np
import cv2

In [5]:
# 下采样: 图片分辨率会变小 (缩小)

img = cv2.imread('./lena.png')

print(img.shape)

# 使用下采样的高斯金字塔对img进行下采样
dst1 = cv2.pyrDown(img)

dst2 = cv2.pyrDown(dst1)

print(dst.shape)

cv2.imshow('img', img)
cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)

cv2.waitKey(0)
cv2.destroyAllWindows()

(512, 512, 3)
(256, 256, 3)


In [ ]:
alex 20:35:50
老师，高斯金字塔的下采样和cv2.resize的缩小在使用场景有什么不同？
下采样只能缩小为原图的1/4, resize任意尺度都可以. 
下采样和resize从原理上就不一样. 下采样是用高斯平滑,然后去掉偶数行和列得到结果. resize是通过线性插值的方式来补全像素点. 

In [6]:
# 上采样: 图片分辨率会变大 (放大)

img = cv2.imread('./lena.png')

print(img.shape)

# 使用上采样的高斯金字塔对img进行上采样
dst1 = cv2.pyrUp(img)

dst2 = cv2.pyrUp(dst1)

print(dst.shape)

cv2.imshow('img', img)
cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)

cv2.waitKey(0)
cv2.destroyAllWindows()

(512, 512, 3)
(256, 256, 3)


In [ ]:
# 不管是上采样还是下采样, 都会丢失图片的一些信息. 

### 高斯金字塔可逆性研究

In [9]:
img = cv2.imread('./lena.png')

dst1 = cv2.pyrDown(img)
dst2 = cv2.pyrUp(dst1)

dst3 = cv2.pyrDown(dst2)
dst4 = cv2.pyrUp(dst3)

cv2.imshow('img', img)
cv2.imshow('dst1', dst4)
cv2.imshow('dst2', dst2)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
# 丢失的细节
cv2.imshow('dst2', img - dst2) # 拉普拉斯金字塔第0层
cv2.imshow('dst4', dst2 - dst4) # 拉普拉斯金字塔第1层. 

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# 因为拉普拉斯金字塔太简单, opencv甚至没有给拉普拉斯金字塔一个api. 

In [20]:
cv2.imshow('dst2', cv2.subtract(img, dst2)) 
cv2.imshow('dst4', img - dst2) 

cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
img - dst2

array([[[  1,   1,   1],
        [  0,   0,   0],
        [  0, 255,   0],
        ...,
        [  7,   7,  12],
        [254, 254,   1],
        [232, 231, 236]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  1,   0,   0],
        ...,
        [ 11,  12,  11],
        [  0,   0, 255],
        [229, 228, 228]],

       [[  0, 255,   0],
        [  1, 255,   0],
        [  2,   1,   1],
        ...,
        [ 10,  12,   8],
        [  1,   3, 255],
        [232, 233, 232]],

       ...,

       [[252, 253, 252],
        [251, 251, 249],
        [  2,   2,   2],
        ...,
        [  2,   3,   4],
        [255,   0,   2],
        [251, 253,   1]],

       [[253, 251, 251],
        [253, 251, 250],
        [  6,   6,   6],
        ...,
        [  0, 255,   3],
        [  0,   1,   4],
        [  1,   2,   5]],

       [[254, 253, 252],
        [255, 253, 252],
        [  7,   8,   8],
        ...,
        [255, 254,   1],
        [  0,   2,   5],
        [  4,   4,   9]]

In [18]:
img[:3]

array([[[128, 138, 225],
        [127, 137, 224],
        [126, 136, 224],
        ...,
        [126, 145, 236],
        [110, 129, 220],
        [ 86, 104, 197]],

       [[127, 137, 224],
        [127, 137, 224],
        [127, 137, 224],
        ...,
        [130, 150, 235],
        [112, 132, 217],
        [ 83, 102, 189]],

       [[127, 137, 224],
        [127, 137, 224],
        [128, 138, 225],
        ...,
        [127, 148, 230],
        [112, 133, 215],
        [ 85, 105, 190]]], dtype=uint8)

In [19]:
dst2[:3]

array([[[127, 137, 224],
        [127, 137, 224],
        [126, 137, 224],
        ...,
        [119, 138, 224],
        [112, 131, 219],
        [110, 129, 217]],

       [[127, 137, 224],
        [127, 137, 224],
        [126, 137, 224],
        ...,
        [119, 138, 224],
        [112, 132, 218],
        [110, 130, 217]],

       [[127, 138, 224],
        [126, 138, 224],
        [126, 137, 224],
        ...,
        [117, 136, 222],
        [111, 130, 216],
        [109, 128, 214]]], dtype=uint8)

In [ ]:
# cv2.subtract 他是小于0的都给0. 