In [1]:
import numpy as np
import cv2

### 查找轮廓

In [3]:
cv2.RETR_EXTERNAL

0

In [11]:
# cv2.findContours
img = cv2.imread('./contours1.jpeg')

# 一般查找轮廓都是使用黑白图. 
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 二值化
thresh, binary = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY)

# cv2.CHAIN_APPROX_SIMPLE只保存角点, cv2.CHAIN_APPROX_NONE保存所有的点. 
contours, hierarchy = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

# 观察opencv中轮廓数据的格式. 首先是一个三维的. shape (点的个数, 1, x,y)
print(contours)
print(contours[0].shape)
print('-------------')
print(hierarchy)

(array([[[  0,   0]],

       [[  0, 435]],

       [[345, 435]],

       [[345,   0]]], dtype=int32), array([[[ 36, 130]],

       [[ 37, 129]],

       [[310, 129]],

       [[311, 130]],

       [[311, 400]],

       [[310, 401]],

       [[ 37, 401]],

       [[ 36, 400]]], dtype=int32), array([[[ 36,  35]],

       [[ 37,  34]],

       [[308,  34]],

       [[309,  35]],

       [[309,  39]],

       [[308,  40]],

       [[ 37,  40]],

       [[ 36,  39]]], dtype=int32))
(4, 1, 2)
-------------
[[[-1 -1  1 -1]
  [ 2 -1 -1  0]
  [-1  1 -1  0]]]


### 绘制轮廓

In [18]:
img = cv2.imread('./contours1.jpeg')

# 一般查找轮廓都是使用黑白图. 
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 二值化
thresh, binary = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY)

# cv2.CHAIN_APPROX_SIMPLE只保存角点, cv2.CHAIN_APPROX_NONE保存所有的点. 
contours, hierarchy = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

# 绘制轮廓
img2 = cv2.drawContours(img.copy(), contours, -1, (0, 0, 255), 2)

cv2.imshow('img', img)
cv2.imshow('img2', img2)

cv2.waitKey(0)
cv2.destroyAllWindows()

### 计算轮廓面积

In [37]:
img = cv2.imread('./a2.jpg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 二值化
binary = cv2.adaptiveThreshold(gray,  255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 9, 0)

contours, _ = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

img_copy = img.copy()
contours2 = []
# 计算轮廓面积
for i in range(len(contours)):
    area = cv2.contourArea(contours[i])
    print(area)
    if area > 100:
        contours2.append(contours[i])



cv2.drawContours(img_copy, contours2, -1, (0, 0, 255), 2)


cv2.imshow('binary', binary)
cv2.imshow('img', img)
cv2.imshow('img_copy', img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

0.0
0.0
0.0
0.0
0.0
0.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
8.0
0.0
0.0
0.0
5.0
0.5
0.0
1.5
0.0
7.0
7.0
1.0
0.5
0.0
0.0
5.5
4.0
8.0
0.5
0.5
0.0
5.5
3.5
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9.0
0.5
7.0
2.0
0.5
0.5
0.0
0.0
1.5
0.5
0.0
0.0
9.0
7.5
0.0
0.0
2.0
0.5
2.5
0.0
0.0
1.0
0.0
4.0
7.0
0.0
0.0
7.5
2.0
2.0
6.0
9.5
2.5
0.0
15.0
3.5
0.0
1.5
0.0
0.0
0.0
4.0
7.0
3.5
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.5
0.0
1.5
0.0
0.0
0.5
0.5
0.0
0.0
3.0
1.0
1.0
2.5
0.0
0.5
0.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
0.5
0.0
0.5
0.0
0.0
0.0
0.0
0.5
15.0
1.0
0.0
0.5
0.0
70.5
0.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.5
2.0
0.0
0.0
7.0
2.0
0.0
0.0
0.0
1.5
0.0
0.0
0.0
0.0
23.0
23.0
0.0
0.0
0.5
0.0
3.5
2.5
0.0
0.0
0.0
6.5
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
7.0
0.0
0.0
0.5
0.0
0.0
39.0
1.0
0.0
0.0
1.5
1.0
1.0
7.5
0.5
0.0
0.0
0.0
3.0
5.0
6.0
0.0
1.0
0.5
0.0
3.0
7.5
0.5
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.5
2.0
0.0
0.5
0.5
0.0
0.0
21.0
0.5
0.0
0.0
0.0
0.5
0

In [36]:
img = cv2.imread('./contours1.jpeg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 二值化
binary = cv2.adaptiveThreshold(gray,  255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 9, 0)

contours, _ = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

img_copy = img.copy()

# 计算轮廓周长
perimeter = cv2.arcLength(contours[0], False)

print(perimeter)
cv2.drawContours(img_copy, contours, 0, (0, 0, 255), 2)


# cv2.imshow('binary', binary)
cv2.imshow('img', img)
cv2.imshow('img_copy', img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

835.9705619812012


In [35]:
1110.97 - (1110.97 / 4)

833.2275

### 多边形逼近和凸包

In [59]:
img = cv2.imread('./hand.png')

# 一般查找轮廓都是使用黑白图. 
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 二值化
thresh, binary = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY)

contours, _ = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
print(contours[0].shape)

# 使用多变形逼近, 减少存储的轮廓点. 
approx = cv2.approxPolyDP(contours[0], 5, closed=True)
print(approx.shape)
img_copy = img.copy()
cv2.drawContours(img_copy, [approx], 0, (0, 0, 255), 2)

cv2.imshow('img', img)
cv2.imshow('img_copy', img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

(379, 1, 2)
(23, 1, 2)


In [60]:
# 凸包
img = cv2.imread('./hand.png')

# 一般查找轮廓都是使用黑白图. 
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 二值化
thresh, binary = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY)

contours, _ = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
print(contours[0].shape)

# 使用多变形逼近, 减少存储的轮廓点. 
approx = cv2.approxPolyDP(contours[0], 5, closed=True)
print(approx.shape)

# 凸包
hull = cv2.convexHull(contours[0])

img_copy = img.copy()
cv2.drawContours(img_copy, [hull], 0, (0, 0, 255), 2)

cv2.imshow('img', img)
cv2.imshow('img_copy', img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

(379, 1, 2)
(23, 1, 2)


### 最小外矩形和最大(up-right)外接矩形

In [67]:
img = cv2.imread('./hello.jpeg')
# 一般查找轮廓都是使用黑白图. 
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 二值化
thresh, binary = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY)

contours, _ = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)


# 最小外接矩形
# 返回的是旋转矩形 Rotated Rect, 包含矩形的起始坐标(x,y), 长宽, 旋转角度. 
rect = cv2.minAreaRect(contours[1])
print(rect)
# boxPoints可以帮助我们把旋转矩形的4个坐标计算出来. 
box = cv2.boxPoints(rect)
print(box)

# 变成整数
box = np.round(box).astype('int64')

# 最大外接矩形
# 返回矩形的x,y, w,h
x, y, w, h = cv2.boundingRect(contours[1])

img_copy = img.copy()
cv2.drawContours(img_copy, [box], 0, (0, 0, 255), 2)

cv2.rectangle(img, (x, y), (x + w, y + h), (0, 0, 255), 2)


cv2.imshow('img', img)
cv2.imshow('img_copy', img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()


((204.9279022216797, 114.22581481933594), (337.7325134277344, 59.939762115478516), 17.70561981201172)
[[ 34.945923  91.41937 ]
 [ 53.1752    34.318855]
 [374.90988  137.03226 ]
 [356.6806   194.13278 ]]


In [ ]:
# 自行尝试外接圆 cv2.minEnclosingCircle