In [1]:
import numpy as np
import cv2

### 全局二值化

In [13]:
img = cv2.imread('./dog.jpeg')

# 转化为灰度图
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 返回阈值和黑白图片
# thresh, dst = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
# inv = inverse 
# thresh, dst = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY_INV)
# 注意trunc得到的不是二值图. 
# thresh, dst = cv2.threshold(gray, 127, 255, cv2.THRESH_TRUNC)# truncate

thresh, dst = cv2.threshold(gray, 127, 255, cv2.THRESH_TOZERO)
thresh, dst = cv2.threshold(gray, 127, 255, cv2.THRESH_TOZERO_INV)
print(thresh)
cv2.imshow('dog', np.hstack((gray, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

127.0


In [14]:
np.unique(dst)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127], dtype=uint8)

In [4]:
np.unique(gray)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

### 自适应二值化

In [18]:
img = cv2.imread('./dog.jpeg')

# 转化为灰度图
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 只有一个返回值
dst = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 19, 0)

cv2.imshow('dog', np.hstack((gray, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
img = cv2.imread('./math.png')

cv2.namedWindow('img', cv2.WINDOW_NORMAL)
cv2.resizeWindow('img', 1080, 720)

# 转化为灰度图
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 返回阈值和黑白图片
thresh, dst = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY_INV)

print(thresh)
cv2.imshow('img', np.hstack((gray, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

127.0


In [25]:
img = cv2.imread('./math.png')

cv2.namedWindow('img', cv2.WINDOW_NORMAL)
cv2.resizeWindow('img', 1920, 1080)

# 转化为灰度图
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


dst = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 3, 0)

print(thresh)
cv2.imshow('img', np.hstack((gray, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

127.0


### 腐蚀操作

In [32]:
# erode
img = cv2.imread('./j.png')

# 定义核
kernel = np.ones((5,5), np.uint8)

dst = cv2.erode(img, kernel)

cv2.imshow('img', np.hstack((img, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

### 获取形态学卷积核

In [37]:
# getStructuringElement
# erode
img = cv2.imread('./j.png')

# 定义核
# kernel = np.ones((5,5), np.uint8)
# cv2.MORPH_RECT矩形卷积核, 使用最多的卷积核
kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (5, 5))
print(kernel)

dst = cv2.erode(img, kernel)

cv2.imshow('img', np.hstack((img, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [42]:
# 腐蚀操作常用于消除一些图片里面我们不需要(不想要)的部分. 
img = cv2.imread('./msb.png')

# 定义核
kernel = np.ones((3,3), np.uint8)

dst = cv2.erode(img, kernel, iterations=2)

cv2.imshow('img', np.hstack((img, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [44]:
# 有一些噪点也可以用腐蚀来去掉. 
img = cv2.imread('./dotj.png')

# 定义核
kernel = np.ones((5,5), np.uint8)

dst = cv2.erode(img, kernel, iterations=2)

cv2.imshow('img', np.hstack((img, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

### 膨胀

In [46]:
# dilate

img = cv2.imread('./j.png')

# 定义核
# kernel = np.ones((5,5), np.uint8)
# cv2.MORPH_RECT矩形卷积核, 使用最多的卷积核
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
print(kernel)

dst = cv2.dilate(img, kernel)

cv2.imshow('img', np.hstack((img, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [50]:
img = cv2.imread('./dotj.png')

# 定义核
kernel = np.ones((5,5), np.uint8)

# 先腐蚀去掉噪声
dst1 = cv2.erode(img, kernel, iterations=2)

# 再膨胀还原
dst2 = cv2.dilate(dst1, kernel, iterations=2)

cv2.imshow('img', np.hstack((img, dst1, dst2)))
cv2.waitKey(0)
cv2.destroyAllWindows()

### 开运算

In [53]:
img = cv2.imread('./dotj.png')

# 定义核
kernel = np.ones((5,5), np.uint8)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
# # 先腐蚀去掉噪声
# dst1 = cv2.erode(img, kernel, iterations=2)

# # 再膨胀还原
# dst2 = cv2.dilate(dst1, kernel, iterations=2)

# 开运算就是腐蚀 + 膨胀
dst = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel, iterations=2)

cv2.imshow('img', np.hstack((img, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [65]:
img = cv2.imread('./msb.png')

# 定义核
kernel = np.ones((5,5), np.uint8)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
# # 先腐蚀去掉噪声
# dst1 = cv2.erode(img, kernel, iterations=2)

# # 再膨胀还原
# dst2 = cv2.dilate(dst1, kernel, iterations=2)

# 开运算就是腐蚀 + 膨胀
dst = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel, iterations=1)

cv2.imshow('img', np.hstack((img, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

### 闭运算

In [63]:
img = cv2.imread('./dotinj.png')

# 定义核
kernel = np.ones((5,5), np.uint8)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))

# 闭运算就是膨胀 + 腐蚀
dst = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel, iterations=2)

cv2.imshow('img', np.hstack((img, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [62]:
img = cv2.imread('./dotinj.png')

# 定义核
kernel1 = np.ones((5,5), np.uint8)
kernel2 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))

dst1 = cv2.dilate(img, kernel1, iterations=2)

dst2 = cv2.erode(dst1, kernel, iterations=2)

# 闭运算就是膨胀 + 腐蚀
# dst = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel, iterations=2)

cv2.imshow('img', np.hstack((img, dst1, dst2)))
cv2.waitKey(0)
cv2.destroyAllWindows()

### 形态学梯度(即边缘)

In [69]:
img = cv2.imread('./j.png')

# 定义核
kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (3, 3))

# 形态学梯度= 原图 - 被腐蚀之后的图 = 边缘
dst = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel, iterations=1)

cv2.imshow('img', np.hstack((img, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

### 顶帽运算(tophat)

In [76]:
img = cv2.imread('./tophat.png')

# 定义核
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (9, 9))

# 顶帽/礼帽
dst = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel, iterations=1)

cv2.imshow('img', np.hstack((img, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [79]:
img = cv2.imread('./msb.png')

# 定义核
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))

# 顶帽/礼帽
dst = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel, iterations=1)

cv2.imshow('img', np.hstack((img, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

### 黑帽操作

In [80]:
img = cv2.imread('./dotinj.png')

# 定义核
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))

# 黑帽: 原图 - 闭运算
dst = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel, iterations=1)

cv2.imshow('img', np.hstack((img, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
课后自行找一些图去练习这些形态学操作. 