In [1]:
import numpy as np
import cv2 

In [7]:
## 位运算中掩码的作用. 
# bitwise_and(src1, src2[, dst[, mask]]) -> dst
# 先src1和src2做与运算, 然后结果再和mask做与运算, 如果与出来的结果是true,就保持原来的值, 如果是False, 就变成0.
cat = cv2.imread('./cat.jpeg')
# 创建一个mask, mask必须是二维的.  mask长宽必须和与运算的图片一样大.
mask = np.zeros((100, 100), np.uint8)

mask[50:100, 50:100] = 255
# roi region of interest
roi = cat[:100, :100]
cv2.imshow('roi1', roi)

# 注意mask尽量写关键词参数, 因为mask前面还有一个dst参数.
roi = cv2.bitwise_and(roi, roi, mask=mask)
cv2.imshow('roi2', roi)

cat[:100, :100] = roi
cv2.imshow('cat', cat)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 图像的基本变换

#### resize的用法

In [9]:
cv2.INTER_NEAREST

0

In [17]:
dog = cv2.imread('./dog.jpeg')
# dog.shape
# new_dog = cv2.resize(dog, (800, 800), interpolation=cv2.INTER_NEAREST)
# new_dog = cv2.resize(dog, (800, 800), interpolation=cv2.INTER_AREA)
# 按比例缩放
new_dog = cv2.resize(dog, (0, 0), fx=2, fy=2)

# cv2.imshow('dog', dog)
cv2.imshow('new_dog', new_dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### 图像的翻转

In [23]:
dog = cv2.imread('./dog.jpeg')

# flipCode=0表示上下翻转
new_dog = cv2.flip(dog, 0)
# 左右翻转
new_dog = cv2.flip(dog, 1)
# 小于0, 表示上下左右翻转. 
new_dog = cv2.flip(dog, -1)
cv2.imshow('new_dog', new_dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### 图像的旋转

In [32]:
cv2.ROTATE_90_CLOCKWISE

0

In [34]:
dog = cv2.imread('./dog.jpeg')

# 旋转180
new_dog = cv2.rotate(dog, cv2.ROTATE_180)
# 顺时针旋转90度
new_dog = cv2.rotate(dog, cv2.ROTATE_90_CLOCKWISE)

# 逆时针旋转90度
new_dog = cv2.rotate(dog, cv2.ROTATE_90_COUNTERCLOCKWISE)

# 使用rotate不能旋转任意角度. 


print(dog.shape, new_dog.shape)
cv2.imshow('dog', dog)
cv2.imshow('new_dog', new_dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

(360, 499, 3) (499, 360, 3)


#### 仿射变换之平移

In [35]:
dog = cv2.imread('./dog.jpeg')
h, w, _ = dog.shape

# 变换矩阵, 必须最少是float32位
M = np.float32([[1, 0, 100], [0, 1, 100]])

# 进行平移操作. 
# opencv中, 一般都是先宽度, 后高度. 
new_dog = cv2.warpAffine(dog, M, dsize=(w, h))

print(dog.shape, new_dog.shape)
cv2.imshow('dog', dog)
cv2.imshow('new_dog', new_dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

(360, 499, 3) (360, 499, 3)


In [36]:
new_dog

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [101, 153, 190],
        [120, 171, 211],
        [134, 186, 226]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [158, 210, 247],
        [ 85, 137, 174],
        [117, 170, 207]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [150, 202, 238],
        [122, 174, 211],
        [ 97, 150, 187]]

In [37]:
M = np.float32([[1, 0, 100], [0, 1, 100], [0, 0, 1]])
new_dog = M @ dog
new_dog

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 499 is different from 3)

In [ ]:
# 课后思考: 如果使用原始的矩阵乘法实现仿射变换. 

In [ ]:
# 以后在深度学习中会使用opencv对图片做一系列的数据增强. 

#### 获取变换矩阵

In [40]:
# cv2.getRotationMatrix2D
dog = cv2.imread('./dog.jpeg')
h, w, _ = dog.shape
# 获取变换矩阵
M = cv2.getRotationMatrix2D((w/2, h/2), 45, 0.5)
print(M)
new_dog = cv2.warpAffine(dog, M, (w, h))

cv2.imshow('dog', dog)
cv2.imshow('new_dog', new_dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[  0.35355339   0.35355339  97.64881874]
 [ -0.35355339   0.35355339 204.57196065]]


In [41]:
# 另一种获取变换矩阵的方法
# getAffineTransform
dog = cv2.imread('./dog.jpeg')
h, w, _ = dog.shape

src = np.float32([[100, 100], [200, 100], [200, 300]])
dst = np.float32([[100, 150], [360, 200], [280, 120]])
M = cv2.getAffineTransform(src, dst)

new_dog = cv2.warpAffine(dog, M, (w, h))
cv2.imshow('dog', dog)
cv2.imshow('new_dog', new_dog)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### 透视变换

In [44]:
img = cv2.imread('./123.png')
print(img.shape)
# 获取变换矩阵
# 原图的4个坐标
src = np.float32([[100, 1100], [2100, 1100], [0, 4000], [2500, 3900]])
dst = np.float32([[0, 0], [2300, 0], [0, 3000], [2300, 3000]])
M = cv2.getPerspectiveTransform(src, dst)
# 得到透视变换的变换矩阵
new_img = cv2.warpPerspective(img, M, (2300, 3000))

cv2.namedWindow('img', cv2.WINDOW_NORMAL)
cv2.resizeWindow('img', 1080, 720)
cv2.imshow('img', img)

cv2.namedWindow('new_img', cv2.WINDOW_NORMAL)
cv2.resizeWindow('new_img', 1080, 720)
cv2.imshow('new_img', new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

(4032, 3024, 3)
