In [1]:
import cv2
import numpy as np

### 通道分离与合并

In [ ]:
img[:] = [b, g, r]

In [8]:
# 创建一个全黑的图片
img = np.zeros((200,200, 3), np.uint8)

# 使用split分离通道, 分割出来的通道是二维的ndarray
b, g, r = cv2.split(img)
# 修改一些颜色
b[10: 100, 10:100] = 127
g[10:100, 10:100] = 255

# 合并通道叫merge
img2 = cv2.merge((b, g, r))

# 展示单通道的图片和合并之后的图片. 
# 单通道的图片就是灰度图, 0表示黑色, 255表示白色. 其他值表示不同的灰度值. 
# 3通道的图片, 每个通道的数值就表示相应颜色的数值.
cv2.imshow('b_g', np.hstack((b, g)))
cv2.imshow('img2', np.hstack((img, img2)))

cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
img

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [25]:
# 不用opencv的api, 我们使用numpy的基础操作也可以实现通道的分离与合并. 
b, g, r = img[:, :, 0], img[:, :, 1], img[:, :, 2]

r[10: 100, 10:100] = 255
g[10:100, 10:100] = 255



# 3个2维ndarray 要合并成一个3维的ndarray


In [27]:
# 这个就是把多个ndarray合并在一起的. 
# np.hstack, np.vstack
img3 = np.concatenate((b.reshape(200, 200, 1), g.reshape(200, 200, 1), r.reshape(200, 200, 1)), axis=-1)
cv2.imshow('img3', img3)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
r[10:100, 10:100]

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [20]:
b

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [17]:
b.reshape(200, 200, 1)

array([[[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       ...,

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]]], dtype=uint8)

### 绘图

#### 画直线

In [35]:
# cv.line()
# 创建背景图片
img = np.zeros((800, 800, 3), np.uint8)
# line(img, pt1, pt2, color[, thickness[, lineType[, shift]]]) -> img
cv2.line(img, (10, 20), (400, 400), (255, 255, 255), 10, 16)


cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### 画矩形

In [38]:
# cv.line()
# 创建背景图片
img = np.zeros((800, 800, 3), np.uint8)
cv2.rectangle(img, (10, 20), (400, 400), (255, 255, 0), 3, 8)


cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### 画圆

In [40]:
img = np.zeros((800, 800, 3), np.uint8)
# circle(img, center, radius, color[, thickness[, lineType[, shift]]])
cv2.circle(img, (400, 400), 100, (255, 255, 0), 3, 16)


cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### 画椭圆

In [45]:
img = np.zeros((800, 800, 3), np.uint8)
# ellipse(img, center, axes, angle, startAngle, endAngle, color[, thickness[, lineType[, shift]]])
# angle就是指椭圆的旋转角度, starangle和endangle控制画椭圆的哪一部分, 0到360就是画一个完整的椭圆
cv2.ellipse(img, (400, 400), (100, 200), 90, 0, 360, [0, 0, 255], 3, 16)


cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### 画多边形

In [53]:
img = np.zeros((800, 800, 3), np.uint8)
# polylines(img, pts, isClosed, color[, thickness[, lineType[, shift]]])
# 点集必须是int32, 本质上是二维, 里面放的是成对x,y坐标
# isClosed表示是否要把多边形封闭起来. 
pts = np.array([[250, 100], [150, 600], [50, 280], [300, 400], [240, 300]], np.int32)
cv2.polylines(img, [pts], True, [0, 0, 255], 3, 16)


cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### 填充多边形

In [57]:
img = np.zeros((800, 800, 3), np.uint8)
# fillPoly(img, pts, color[, lineType[, shift[, offset]]])
pts = np.array([[250, 100], [150, 300], [50, 280], [300, 400], [240, 300]], np.int32)
# fillpoly因为是填充的多边形, 没有thickness这个参数. 也没有isClosed参数
cv2.fillPoly(img, [pts], [0, 255, 255], 16)


cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### 显示文本

In [58]:
img = np.zeros((800, 800, 3), np.uint8)

# putText(img, text, org, fontFace, fontScale, color[, thickness[, lineType[, bottomLeftOrigin]]])
text = '你好, opencv'
# org就是显示文本时的起始坐标, fontFace字体, fontScale字体的大小
# opencv是默认不能显示中文字体的.因为没有提供中文字体文件
cv2.putText(img, text, (50, 300), cv2.FONT_HERSHEY_COMPLEX, 5, [0, 0, 255])

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# 如果实在要在图片里面绘制中文. 那么要换个包了, opencv是做不到了. 
# python 处理图片最万能的包, 是pillow ,即PIL

In [62]:
from PIL import ImageFont, ImageDraw, Image

img = np.zeros((800, 800, 3), np.uint8)

# 从字体文件中导入字体.
font = ImageFont.truetype('./msyhbd.ttc')
# 创建一个pillow的图片
img_pil = Image.fromarray(img)
draw = ImageDraw.Draw(img_pil)
# 利用draw去绘制中文
text = '你好, opencv'
# fill是RGBA
draw.text((100, 250), text, font=font, fill=(0, 0, 255, 0))

# img_pil
# 变回ndarray方便在opencv中显示
img = np.array(img_pil)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# 作业 按住鼠标左键, 就可以绘制图形. 通过键盘上的按键控制绘制不同的图形, 基本图形有直线, 圆, 矩形. 